### ISSUE TITLE
Optional ceil rate, performance implications

### ISSUE THREAD

**Issue by rchac** [rchac/LibreQoS#105]
I see in tc manual so interesting thing:
```
       ceil rate
              Maximum rate at which a class can send, if its parent has
              bandwidth to spare.  Defaults to the configured rate,
              which implies no borrowing
```

If ceil is optional could we just set the rates (as ceil) in `linux_tc.txt` when there is a flat design? Is that possible?
Pros: HTB will have much less work to do when no borrowing is set.

_Originally posted by @interduo in https://github.com/rchac/LibreQoS/issues/103#issuecomment-1249462171_

**Comment by rchac** [comment]
@interduo 

> HTB will have much less work to do when no borrowing is set.

We'd have to test to find out. I don't know if that would impact CPU use by much.

You can test using this branch I made https://github.com/rchac/LibreQoS/blob/interduo-ceil-test/v1.2/LibreQoS.py

**Comment by interduo** [comment]
I will test that in near future.

**Comment by interduo** [comment]
I am willing to test TBF instead of HTB also.

**Comment by interduo** [comment]
I tested it - there is no so big difference using https://github.com/rchac/LibreQoS/commit/f5a59aeb36910447422db77abd642266f764f1eb - so please close the branch.

Also the differences are very hard to distinguish because of that the network throughput differs very much (in may ways) in time even that the const rate is above few gigs.
