### ISSUE TITLE
XDP & HT Cores

### ISSUE THREAD

**Issue by Belyivulk** [rchac/LibreQoS#38]
This is more of a question than a issue. 

We've observed that XDP doesn't seem to map queues to hyperthreaded cores. In Ubuntu they appear as physical CPU's but it just doesn't want to touch them. The CPU is a 18 core / 38 thread Intel Xeon Gold; only the first 18 cores seem to get used for this process with the balance remaining relatively idle.

Is this expected behavior or a potential bug?

**Comment by rchac** [comment]
How many RX/TX queues does your NIC have? You can run `ethtool -l  INTERFACE_HERE` to find out.

**Comment by Belyivulk** [comment]
Rather frustratingly; it moves with the number of cores available. So when i run it now (with HT off)

root@qos-box:/home/uberadmin/libreqos/v1.1# ethtool -l ens1f0
Channel parameters for ens1f0:
Pre-set maximums:
RX:             n/a
TX:             n/a
Other:          1
Combined:       18
Current hardware settings:
RX:             n/a
TX:             n/a
Other:          1
Combined:       18

**Comment by Belyivulk** [comment]
As an aside, we're now also seeing this error sporadically (i say sporadically; its consistent and repeatable)

"WARN: Bad config mismatch ip handle:0x100213 (major:0x10) not matching TXQ-config:0xA
Misconf: But allowing to continue"

if you understand the reason for it, we'd love to address it

**Comment by Belyivulk** [comment]
Sorry for the spam, also, i was wrong - it only uses cores 0-15. 16 + are untouched

**Comment by Belyivulk** [comment]
So we've disabled HT; still only the first ~16 cores get used (2 sit idle); and we get the error:

""WARN: Bad config mismatch ip handle:0x100213 (major:0x10) not matching TXQ-config:0xA
Misconf: But allowing to continue"" 

in places. Any thoughts on those two issues?

**Comment by rchac** [comment]
How often does that error appear? Perhaps 2-8 times after each run? I ask because it might be due to an error related to the major tc handle being a 16-bit integer.

I noticed this section in xdp-cpumap-tc's [common_user.c file](https://github.com/xdp-project/xdp-cpumap-tc/blob/master/src/common_user.c#L67):
```	ip_htb_major = TC_H_MAJ(ip_info->tc_handle) >> 16;
	if (txq_cfg.htb_major != ip_htb_major) {
		if (verbose)
			fprintf(stderr,
				"WARN: Bad config mismatch "
				"ip handle:0x%X (major:0x%X) "
				"not matching TXQ-config:0x%X\n",
				ip_info->tc_handle, ip_htb_major,
				txq_cfg.htb_major);
		return false;
	}
	return true;```

I'm wondering if having more than 16 CPU cores leads to the major counter on LibreQoS.py to iterate too high (past 16). If so I can try to resolve this, I just want to be sure it's related to what I think it is.

**Comment by rchac** [comment]
I think I figured it out. Appears to be that class, qdisc, and cpu-core handles need to be converted to hex to prevent misinterpretation as hex by xdp-cpumap-tc. Will test overnight and if it works I will provide you the sample to see if it resolves the issues for you.

**Comment by Belyivulk** [comment]
That's awesome news, thank you :) We've been working to get 40gigs through the box today and it fights us at every turn! Hopefully by this time tomorrow we'll be able to test that as well.

**Comment by rchac** [comment]
Here's a revised version of the file. Please let me know if this resolves things for you. [https://github.com/rchac/LibreQoS/blob/main/v1.1/LibreQoS.py](https://github.com/rchac/LibreQoS/blob/main/v1.1/LibreQoS.py)

**Comment by Belyivulk** [comment]
Will do; thank you :) To be clear; we're expecting this fix to resolve the error messages and allow us to use beyond 16 cores?

**Comment by rchac** [comment]
That's correct. It should resolve the error message, as well as allow for as many cores as xdp-cpumap-tc can handle (up to 32 or 64 i believe).

**Comment by Belyivulk** [comment]
Awesome :) Will let you know soon

**Comment by Belyivulk** [comment]
Alrighty; we're no longer getting this error

""WARN: Bad config mismatch ip handle:0x100213 (major:0x10) not matching TXQ-config:0xA
Misconf: But allowing to continue""

It's all working as expected on that front. 

The last 2 cores (16 & 17) look to be being used (in top i see cpumap/17/map:4) but they're not nearly as balanced as the first 16 (the first 16 are floating around 22% used, where as the last 2 are around 10%) - with nearly 10gig of production traffic flowing through.

Is there a better way to interrogate / break down what sites/ips are being assigned to which core that may help us understand this a bit better?

**Comment by Belyivulk** [comment]
never mind my question above ^^ ; turns out we're already working on that haha. Most of what we do / find will make its way to you as we go along.

**Comment by jgamos** [comment]
tried using the updated LibreQoS.py and I'm seeing errors
Is the update for OP solution only?

~
ubuntu@ubuntu:~/LibreQoS/v1.1$ sudo python3 ./LibreQoS.py
tc filter delete dev enp1s0f0
Error: Class doesn't support blocks.
We have an error talking to the kernel
tc filter delete dev enp1s0f0 root
Error: Specified class doesn't exist.
We have an error talking to the kernel
tc qdisc delete dev enp1s0f0 root
Error: Cannot delete qdisc with handle of zero.
tc qdisc delete dev enp1s0f0
Error: Failed to find qdisc with specified handle.
tc filter delete dev enp1s0f1
Error: Class doesn't support blocks.
We have an error talking to the kernel
tc filter delete dev enp1s0f1 root
Error: Specified class doesn't exist.
We have an error talking to the kernel
tc qdisc delete dev enp1s0f1 root
Error: Cannot delete qdisc with handle of zero.
tc qdisc delete dev enp1s0f1
Error: Failed to find qdisc with specified handle.
This Network Interface Card has 4 queues avaialble.
Traceback (most recent call last):
  File "/home/ubuntu/LibreQoS/v1.1/./LibreQoS.py", line 241, in <module>
    refreshShapers()
  File "/home/ubuntu/LibreQoS/v1.1/./LibreQoS.py", line 106, in refreshShapers
    cpuCount = multiprocessing.cpu_count()
NameError: name 'multiprocessing' is not defined
ubuntu@ubuntu:~/LibreQoS/v1.1$

**Comment by rchac** [comment]
Great. And do not worry, that's normal console output. Your shaping should work correctly now.

**Comment by rchac** [comment]
> never mind my question above ^^ ; turns out we're already working on that haha. Most of what we do / find will make its way to you as we go along.

Hello Belyivulk. Just curious, how much bandwidth have you been able to push through LibreQoS?

**Comment by Belyivulk** [comment]
Heya :) So far ~11gbps in the download direction; although we keep running into unexpected complications elsewhere :)

Today we've deployed what we think looks like the final configuration (its taken some doing); will let you know how that goes.

As an aside; we've been unable to shape by Site and AP in the network.json; i.e.:

Site01
    AP01
     Client1
     Client2
   AP02
     Client3

AP03
     Client4

So what we've been doing as a nasty hack to get up and running is to give every AP a parentl "site" with very high limits (so the the ceiling is never reached for the parent site) but my instinct is that, that is extremely inefficient. 

Any thoughts / ideas on that one?

Finally; how does one contribute to the readme.md on github? I see atleast one typo :)

Cheers!

**Comment by Belyivulk** [comment]
Should add, thats 11gbps of production traffic (~5000 real end users traffic passing through)

**Comment by rchac** [comment]
That is really exciting to hear! How cool.

1) On ispConfig.py, are you using fqOrCAKE = 'cake diffserv4' or fqOrCAKE = 'fq_codel'? Usually fq_codel allows for less CPU use and greater throughput. CAKE is great for ISP networks where the diffserv option does the heavy lifting of optimizing Netflix or games, but in most cases fq_codel uses half the CPU resources with no perceptible drawbacks.

2) Regarding network topology:

If I'm understanding correctly, your network.json would look like:
```
{
	"Site01": {
		"downloadBandwidthMbps": 15000,
		"uploadBandwidthMbps": 15000,
		"children": {
			"AP01": {
				"downloadBandwidthMbps": 15000,
				"uploadBandwidthMbps": 15000
			},
			"AP02": {
				"downloadBandwidthMbps": 15000,
				"uploadBandwidthMbps": 15000
			},
		}
	},
	"AP03": {
		"downloadBandwidthMbps": 15000,
		"uploadBandwidthMbps": 15000
	}
}
```
With a Shaper.csv like this:
![image](https://user-images.githubusercontent.com/22501920/178128577-11640fb5-189b-46f3-9705-8b6c3066b44b.png)

Am I getting that correctly? In the new v1.1 network.json setup, you should be able to assign any host to a parent node, whether that's a top level node (usually a site) or second level node (usually an AP). In this example, Site01 and AP03 are the top level nodes, which are bound to the CPU as the top of the HTB tree. Ideally, for max throughput, you'll want as many top level nodes as you have CPU cores, with hosts evenly assigned to each top level node. That should maximize throughput.

3) Regarding the README, you are welcome to either DM me what to change, or submit a [pull request](https://github.com/rchac/LibreQoS/pulls). Thanks!

**Comment by Belyivulk** [comment]
Yeah, it's working really very well from what we can measure so far!

We're using cake diffserve4 and that seems to be magical if not CPU intensive. We could give fq_codel a shot for sure; what i wasn't clear on was if cake was doing some sort of classification itself; or if it relies on something like dscp or other packet marks / flags coming in from upstream to classify traffic into the correct priority queues. 

Your network.json and shaper.csv look correct for what we've been trying to achieve; yes. What we observed when doing that was that all traffic appeared to be bound to one core( both site01 and ap03) and if memory serves (we can retest) i don't think children under ap03 shaped at all.

If we created a network.json with NO sites at all; but only AP's we'd expect to see the CPU they get assigned to cycle through 0-17 over and over until it was done, yeah? That should achieve some degree of balance across cores? My key concern with creating 18 "top level nodes - i.e sites" and then nesting the AP's and their hosts under that (coming from a Mikrotik land) is that we are (i think) in effect handling the same packet more than necessary; which I presume chews cycles? 

As ever, thank you for the help here :)

**Comment by Belyivulk** [comment]
Looks like you found the typo lol. good thing, because i can't figure out how to DM. For someone working in technology i seem to suck at working github.

**Comment by rchac** [comment]
> We could give fq_codel a shot for sure; what i wasn't clear on was if cake was doing some sort of classification itself; or if it relies on something like dscp or other packet marks / flags coming in from upstream to classify traffic into the correct priority queues.

fq_codel still has flow isolation and basically gives everything equal fair treatment. CAKE diffserv slices traffic into Bulk, Best Effort, Video, and Voice. More [here](https://www.bufferbloat.net/projects/codel/wiki/CakeTechnical/).

> Your network.json and shaper.csv look correct for what we've been trying to achieve; yes. What we observed when doing that was that all traffic appeared to be bound to one core( both site01 and ap03) and if memory serves (we can retest) i don't think children under ap03 shaped at all.

They should each be tied to distinct CPU cores, assuming Shaper.csv correctly listed the Parent Node for each host. Shaper.csv host entries without a corresponding Parent Node default to the first core. That may be involved.

> If we created a network.json with NO sites at all; but only AP's we'd expect to see the CPU they get assigned to cycle through 0-17 over and over until it was done, yeah? That should achieve some degree of balance across cores?

For the purposes of v1.1, Sites and APs are kind of flexible in definition. Basically top-level parent nodes are what get allocated to distinct CPU cores, and those could be APs or Sites (as we defined them in v1.0 and prior). And yes, top-level parent nodes cycle from core 0-17 then wrap around again. So in your example, Site01 and AP03 would be top-level parent nodes, each getting their own CPU core.

Ideally you want as many top-level parent nodes as you have cores, or parent node quantity being a multiple of the core count. So if you have 18 cores, having a 18, 36, 54, etc top level parent nodes would be ideal to evenly distribute load across CPU cores.

>My key concern with creating 18 "top level nodes - i.e sites" and then nesting the AP's and their hosts under that (coming from a Mikrotik land) is that we are (i think) in effect handling the same packet more than necessary; which I presume chews cycles?

In this case, that is not the concern. It won't waste cycles. Basically, each CPU gets a a Hierarchy Token Bucket - which can usually handle around 4Gbps of throughput. Each top-level parent node basically becomes the top of that HTB, dictating bandwidth limits to any child nodes or clients below. xdp-cpumap-tc quickly moves ingress traffic matching the IP filter to go to the corresponding CPU core, and whatever matching HTB exists there. That is done to avoid the single-core bottleneck that HTB would otherwise experience (4Gbps max). There have been some attempts to make HTB truly multi-core with something called [Lockless Token Bucket](https://lwn.net/Articles/825445/), but development efforts of that seem to be at a standstill. As our workaround, to maximize throughput while circumventing the "qdisc lock problem" that would otherwise tie all HTB traffic to one CPU, we use XDP to move matched IP traffic to separate cores, before HTB processing even begins. The HTBs for each core don't know about each-other, so we cannot truly enforce a perfect bandwidth ceiling overall, but it tends to work quite well as a workaround until Linux kernel developers have a more elegant solution we can use.

The closer you can get the number of top-level parent nodes to the CPU core count, or a multiple of the CPU core count, the more efficient and balanced throughput will be.

**Comment by Belyivulk** [comment]
Thank you for the comprehensive reply :)

This seems to go a long way to explaining the CPU usage we were seeing prior to defining the subscribers in the shaper.csv (it was very high). Since defining *most* of the subscribers and their AP's in shaper.csv and network.json, cpu usage has decreased dramatically (from nearly 70% of 18x3ghz cores) to just under 30% last night (with ~11gig/sec of throughput). We'll continue to try to refine and balance as best we can.

From everything I can read cake is superior to fq_codel; aside from trying to save CPU is there any other reason to pick fq_codel over cake?

Finally; if you were running a network of this scale through LibreQoS; how would you go about determining & measuring that it is working as desired? Am really struggling with that last bit :)

**Comment by rchac** [comment]
That's great to hear!

If you're able to keep CPU use under 70%, just stick with CAKE - it's awesome. On my ISP network, support calls from gamers (probably the most latency-sensitive end-users we deal with) dropped off completely. We get a lot of end-users saying video conference calls are more stable. Fq_codel still helped a lot at first, but switching to CAKE seems to have done some real magic with diffserv.

I'm imagining you have a lot of clients both in-person and/or behind VPN. Both fq_codel and CAKE really help to optimize latency when an end-user does VoIP or video conferencing over a VPN tunnel. Let's say the average WFH user has a limited upload of 10Mbps (standard DOSCIS cable internet, highly-asymmetrical). By setting such a client's upload max to 8Mbps, you can prevent packet loss on upload while they're video conferencing - and maintain call stability even if OneDrive starts a backup while they're on a call. It really helps to keep things smooth during those kind of scenarios. Additionally, the perceived "snappiness" of web browsing tends to improve even if they're not maxing out bandwidth. For tasks like video conferencing I would anticipate a noticeable quality and stability improvement for a good chunk of end-users.

With regard to measuring impact - I would try:
1) Graphing throughput with InfluxDB to see how close each client gets to their ceiling, and whether LibreQoS is saving APs or Sites from hitting their ceilings (which would otherwise trigger packet loss).
2) I'd poll end-users who have had performance issues before, and compare their experience after a week of their connection being shaped. For my ISP network, polled end-users consistently reported a "smoother" experience.
3) You could also pick a handful of client machines and run [Waveform Bufferbloat](https://www.waveform.com/tools/bufferbloat), with LibreQoS on and off. That tends to be a good indicator of latency under load. Also it's a simple metric to interpret and show to higher-ups or other networking team members.

For a more long-term solution - I'm working toward getting [eBPF-based PPing](https://github.com/xdp-project/bpf-examples/tree/master/pping) to work with LibreQoS. Using xdp-tools, it should be possible to load it even after xdp-cpumap-tc runs. Right now, regular PPing is just to CPU intensive past 1Gbps, so getting automatically graphed tcp latency stats probably isn't viable yet for a network of your size. Once we have eBPF PPing integrated, it should be easier to graph latency before and after LibreQoS shaping is applied. That will help to sort of "prove" performance impact beyond just the positive feedback from end-users. 🙂

If you encounter any quirks in the code, or opportunities for me to improve the code to help it work better for your deployment, please let me know.

**Comment by Belyivulk** [comment]
Cheers for all that :) We'll keep chipping away at it and hopefully before too long you'll see some contributions from us :) 

Can we help in any way with getting eBPF going? We found what you've said, regular PPing just nailed CPU past a certain point, so we've had to turn that off. So if we can help in anyway...absolutely keen.

Cheers again for all the very prompt help and detailed replies. Really helps!
