### ISSUE TITLE
v1.1 - doubled line

### ISSUE THREAD

**Issue by interduo** [rchac/LibreQoS#44]
@rchac there is doubled line:

```
python3 -m pip install ipaddress schedule influxdb-client requests flask
sudo python3 -m pip install ipaddress schedule influxdb-client requests flask
```

This line:
`sudo python3 -m pip install ipaddress schedule influxdb-client requests flask`
is enough. Am I right?

**Comment by rchac** [comment]
I had thought the first line was needed in order to install them for the current user only (first line), while the second line was needed to install them for the root user only (which will run the LibreQoS systemctl service). I'm not sure if the sudo version installs for all users besides just root.

**Comment by interduo** [comment]
I tested this carefully - this is ok.
It needs to be `sudo pip install` and `pip install` when we use LibreQoS as non-root user.

**Comment by rchac** [comment]
Appreciate you testing this to confirm, thanks!
