### ISSUE TITLE
Are we using AF_XDP ?

### ISSUE THREAD

**Issue by marsalans** [rchac/LibreQoS#70]
[https://01.org/linuxgraphics/gfx-docs/drm/networking/af_xdp.html](https://01.org/linuxgraphics/gfx-docs/drm/networking/af_xdp.html)

[https://pantheon.tech/what-is-af_xdp/](https://pantheon.tech/what-is-af_xdp/)

**Comment by rchac** [comment]
We do use XDP, but as I understand it, we do not use AF_XDP with xdp-cpumap-tc. AF_XDP would bypass the rest of the kernel networking stack. xdp-cpumap-tc just does XDP_Redirect to move incoming packets to the appropriate CPU core, where Linux Traffic Control then takes over. It uses XDP_Redirect so that incoming IP traffic is sent to the correct corresponding HTB for that IP's traffic.
