### ISSUE TITLE
validator: Customer Ceil over the generatedPNDownloadMbps gives no error

### ISSUE THREAD

**Issue by interduo** [rchac/LibreQoS#93]
I found small bug in validator/generator:

generatedPNDownloadMbps = 6000
generatedPNUploadMbps = 6000
Add customer (with a ceil over the generated parrent node)
704, 3, 64, 100,,,"172.18.181.9",,50,50,7000,7000, KOMENTARZ

it shows no error - and generates linux_tc.txt with this crazy rates ;-)

**Comment by rchac** [comment]
It shows no error because it squishes down the ceil to that of the parent node. It uses a minimum between the ceil provided in the entry, and that of the parent node. So it will never exceed the parent node's ceil. I have now added a warning though so the operator is aware that is happening. https://github.com/rchac/LibreQoS/commit/f580baafac3f65aba7dd5649fbc04f8e0e466f27
